export const geneticAnalystsDataMock = {
    accountId: "string",
    services: ["string"],
    qualifications: ["string"],
    info: {
        boxPublicKey: "0x8d2f0702072c07d31251be881104acde7953ecc1c8b33c31fce59ec6b0799ecc",
        firstName: "string",
        lastName: "string",
        gender: "string",
        dateOfBirth: 0,
        email: "string",
        phoneNumber: "string",
        specialization: "string",
        profileLink: "string",
        profileImage: "string",
    },
    stakeAmount: 0,
    stakeStatus: 'Unstaked',
    verificationStatus: "Unverified",
    availabilityStatus: 'Unavailable',
	unstakeAt: 0,
	retrieveUnstakeAt: 0,
};