export const geneticAnalystsDataMock = {
    accountId: "string",
    services: ["string"],
    qualifications: ["string"],
    info: {
        boxPublicKey: "string",
        firstName: "string",
        lastName: "string",
        gender: "string",
        dateOfBirth: 0,
        email: "string",
        phoneNumber: "string",
        specialization: "string",
        profileLink: "string",
        profileImage: "string",
    },
    stakeAmount: 0,
    stakeStatus: 'Unstaked',
    verificationStatus: "Unverified",
    availabilityStatus: 'Unavailable',
	unstakeAt: 0,
	retrieveUnstakeAt: 0,
};